### ISSUE TITLE
writing multiple files doesn't work when owner is set to anything beside root on one of them

### ISSUE THREAD

**Issue by aebaid** [ninjarobot/FsCloudInit#2]
### Problem:
Passing in the following cloudConfig object to Farmers custom_data property on a [virtual machine](https://compositionalit.github.io/farmer/api-overview/resources/virtual-machine/)
```
cloudConfig {
    write_files [
        writeFile {
            path "/var/lib/data/hello"
            content "hello world"
            owner "root:root"
            permissions "400"
        } 
        writeFile {
            path "/var/lib/data/helloworld"
            content "hello world"
            owner "ubuntu:ubuntu"
            permissions "400"
        }
    ]
}
|> Writer.write
```

### Generated String:
```
#cloud-config
write_files:
- encoding: b64
  content: aGVsbG8gd29ybGQ=
  owner: root:root
  path: /var/lib/data/hello
  permissions: '0400'
- encoding: b64
  content: aGVsbG8gd29ybGQ=
  owner: ubuntu:ubuntu
  path: /var/lib/data/helloworld
  permissions: '0400'
```

### Expected Results:
* Two files getting generated with names hello, and helloworld.

### Actual Results:
* Only a single file gets generated with name hello.

### Workaround:
The following configuration is working when owner on both files is set to root:root. 
```
cloudConfig {
    write_files [
        writeFile {
            path "/var/lib/data/hello"
            content "hello world"
            owner "root:root"
            permissions "400"
        } 
        writeFile {
            path "/var/lib/data/helloworld"
            content "hello world"
            owner "root:root"
            permissions "400"
        }
    ]
}
|> Writer.write
```
