### ISSUE TITLE
ownership is not respected when writing a file

### ISSUE THREAD

**Issue by aebaid** [ninjarobot/FsCloudInit#3]
### Problem:
Passing in the following cloudConfig object to Farmers custom_data property on a [virtual machine](https://compositionalit.github.io/farmer/api-overview/resources/virtual-machine/)
```
cloudConfig {
    write_files [
        writeFile {
            path "/home/ubuntu/.ssh/id_rsa"
            content "some ssh key"
            owner "ubuntu:ubuntu"
            permissions "400"
        }
    ]
}
|> Writer.write
```

### Generated String:
```
#cloud-config
write_files:
- encoding: b64
  content: c29tZSBzc2gga2V5
  owner: ubuntu:ubuntu
  path: /home/ubuntu/.ssh/id_rsa
  permissions: '0400'
```

### Expected Results:
* File owner is set to ubuntu

### Actual Results:
* File owner is set to root

### Work around:
To fulfill the above need, you'd have to run an additional command to set ownership on the file.
```
cloudConfig {
    write_files [
        writeFile {
            path "/home/ubuntu/.ssh/id_rsa"
            content "hello world"
            owner "root:root"
            permissions "400"
        }
    ]
    runCmd { 
        "sudo chown ubuntu:ubuntu /var/lib/data/helloworld".Split null
    }
}
|> Writer.write
```
